export const data = {
  overall: [
    {
      handle: "@nathanf",
      statistic: "Followers",
      statNo: "1987",
      up: true,
      count: 12,
      src: "/images/icon-facebook.svg",
      platform: "facebook",
    },
    {
      handle: "@nathanf",
      statistic: "Followers",
      statNo: "1044",
      up: true,
      count: 99,
      src: "/images/icon-twitter.svg",
      platform: "twitter",
    },
    {
      handle: "@realnathanf",
      statistic: "Followers",
      statNo: "11k",
      up: true,
      count: 1099,
      src: "/images/icon-instagram.svg",
      platform: "instagram",
    },
    {
      handle: "Nathan F.",
      statistic: "Subscribers",
      statNo: "8239",
      up: false,
      count: 144,
      src: "/images/icon-youtube.svg",
      platform: "youtube",
    },
  ],
  today: [
    {
      stat: "Page Views",
      number: 87,
      percent: 3,
      src: "/images/icon-facebook.svg",
      up: true,
    },
    {
      stat: "Likes",
      number: 52,
      percent: 2,
      src: "/images/icon-facebook.svg",
      up: false,
    },
    {
      stat: "Likes",
      number: 5462,
      percent: 2257,
      src: "/images/icon-twitter.svg",
      up: true,
    },
    {
      stat: " Profile Views",
      number: "52k",
      percent: 1375,
      src: "/images/icon-twitter.svg",
      up: true,
    },
    {
      stat: "Retweets",
      number: 117,
      percent: 303,
      src: "/images/icon-instagram.svg",
      up: true,
    },
    {
      stat: "Likes",
      number: 507,
      percent: 553,
      src: "/images/icon-instagram.svg",
      up: true,
    },
    {
      stat: "Likes",
      number: 107,
      percent: 19,
      src: "/images/icon-youtube.svg",
      up: false,
    },
    {
      stat: "Total Views",
      number: 1407,
      percent: 12,
      src: "/images/icon-youtube.svg",
      up: false,
    },
  ],
};
